name: Noctora
version: 1.0
main: me.itsadamly.noctora.Main
api-version: 1.17

commands:

  playerinfo:
    description: Displays the player's info on a scoreboard.
    aliases: [sb, playerbox, pb]
    usage: /<command>

  atm:
    description: Display ATM.
    usage: /<command>

depend: [Vault]
softdepend: [PlaceHolderAPI]